### ISSUE TITLE
Strange error when data unavailable

### ISSUE THREAD

**Issue by revodavid** [walkerke/idbr#1]
Trying to access data that isn't provided by the API gives a confusing parse error:

```
> idb1('JA', 1960:1961, sex = 'male')
No encoding supplied: defaulting to UTF-8.
Error: parse error: premature EOF

                     (right here) ------^
```

**Comment by walkerke** [comment]
Thanks for pointing this out - I have a few things like that to fix before sending to CRAN.  It's on my to-do list.

**Comment by walkerke** [comment]
I've updated with a more informative error message that captures invalid JSON returned by the API and gives some tips to users on what might have caused the error.  Capturing specific errors is more complicated as there are many reasons why invalid API calls would have been sent; this could be worked out but would require a refactor of a good chunk of the code which I don't have time for at the moment.  As such I'm going to ship to CRAN and look to improve error handling even more with future versions.
