### ISSUE TITLE
Wrong error when using non-active API key

### ISSUE THREAD

**Issue by brandnerl** [walkerke/idbr#3]
When the Census API key has not yet been activated, any query results in the following error:

`Error: You have supplied an invalid query.  Consider revising your year selection (IDB data begin at 1950, and are not available for many countries until 1990), or use idb_variables() or idb_concepts() to view valid choices of variables and concepts.`

**Comment by walkerke** [comment]
A different error message should appear when `idb_api_key` hasn't been set: 

``` r
> library(idbr)
> idb1('US', 2016)
Error in idb1("US", 2016) : 
  A Census API key is required.  Obtain one at http://api.census.gov/data/key_signup.html, and then supply the key to the `idb_api_key` function to use it throughout your idbr session.
```

The error message you are citing should appear when an incorrect API key has been specified: 

``` r
> idb_api_key('XXXXXXX')
> idb1('US', 2016)
No encoding supplied: defaulting to UTF-8.
Error: You have supplied an invalid query.  Consider revising your year selection (IDB data begin at 1950, and are not available for many countries until 1990), or use `idb_variables()` or `idb_concepts()` to view valid choices of variables and concepts.
```

This is something I do need to fix with the next release.  I want to make the error messages more informative (tell users what they got wrong) but this may require some re-factoring to get this just right.
